#
# Copyright (C) 2025 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/amazon/kodiak

# Architecture
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait

# Bootloader
TARGET_2NDINIT_DIR := /system/etc/
TARGET_2NDINIT_FILE := resize_user_data.sh
TARGET_HAS_LOCKED_BOOTLOADER := true

# Display
HAVE_ADRENO_SOURCE := false
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so
TARGET_USES_ION := true
USE_OPENGL_RENDERER := true

# Global flags
COMMON_GLOBAL_CFLAGS += -DAMAZON_LOG

# Filesystems
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE   := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE    := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true

# Partitions
BOARD_FLASH_BLOCK_SIZE := 13107
BOARD_BOOTIMAGE_PARTITION_SIZE ?= 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE ?= 10485760
BOARD_CACHEIMAGE_PARTITION_SIZE ?= 1717986304
BOARD_SYSTEMIMAGE_PARTITION_SIZE ?= 2147483648
BOARD_USERDATAIMAGE_PARTITION_SIZE ?= 23282564608

TARGET_COPY_OUT_SYSTEM := system
TARGET_COPY_OUT_VENDOR := system/vendor

# Platform
BOARD_USES_QCOM_HARDWARE := true
TARGET_BOARD_PLATFORM := msm8974
TARGET_BOOTLOADER_BOARD_NAME := MSM8974
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true
TARGET_USES_QCOM_BSP := true

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.qcom

# Recovery (TWRP)
ifeq ($(RECOVERY_VARIANT),twrp)
DEVICE_RESOLUTION := 720x1280
TW_NO_USB_STORAGE := false
TW_TARGET_USES_QCOM_BSP := true
TW_NO_EXFAT := true
TW_NO_EXFAT_FUSE := true
TW_INCLUDE_CRYPTO := true
TW_NO_LEGACY_PROPS := true
TW_ALWAYS_RMRF := true
TW_THEME := portrait_hdpi
endif

# Inherit the prebuilt kernel files
include device/amazon/kodiak-kernel/BoardConfigKernel.mk

# Inherit the proprietary files
-include vendor/amazon/kodiak/BoardConfigVendor.mk
